defaults:
  - process: process1
  - model: model1
  - _self_

raw: 
  path: data/raw/raw_ch4.joblib
  path_iasi_noise: data/raw/iasi_noise_matrix.joblib
  path_orth_base: data/raw/orth_base.joblib

processed:
  dir: data/processed
  name_input: processed_input.joblib
  path_input: ${processed.dir}/${processed.name_input}
  name_output: processed_output.joblib
  path_output: ${processed.dir}/${processed.name_output}

#final:
#  dir: data/final
#  name: final.csv
#  path: ${final.dir}/${final.name}